dev:
\tuv run uvicorn app.app:create_app --factory --reload --loop asyncio

test:
\tuv run python -m pytest

migrate:
\tuv run alembic upgrade head

revision:
\tuv run alembic revision -m "new migration"

